### ISSUE TITLE
在线查询时出现错误

### ISSUE THREAD

**Issue by DolaBMOon** [ChestnutHeng/Wudao-dict#10]
wd -o ####

Traceback (most recent call last):
  File "WudaoCommand.py", line 118, in <module>
    main()
  File "WudaoCommand.py", line 114, in main
    app.query()
  File "WudaoCommand.py", line 85, in query
    word_info = get_text(self.word)
  File "/home/dolabmoon/Wudao-dict-master/wudao-dict/src/WudaoOnline.py", line 36, in get_text
    root = bs4.BeautifulSoup(content, "lxml")
  File "/usr/local/lib/python3.5/dist-packages/bs4/__init__.py", line 165, in __init__
    % ",".join(features))
bs4.FeatureNotFound: Couldn't find a tree builder with the features you requested: lxml. Do you need to install a parser library?

**Comment by ChestnutHeng** [comment]
你好，估计是python库没有安装完全
试试
pip install lxml
或者
pip3 install lxml
有问题可以多百度

**Comment by SerendpityZOEY** [comment]
Why I got wd command not found error after running the setup script?(I'm a mac user)

**Comment by ChestnutHeng** [comment]
@SerendpityZOEY I am not a macbook user, but it could be used on MacOS.
you should copy wd(a sh file in wudao-dict folder) into your system PATH(environment variables) folder
