### ISSUE TITLE
新版本不能使用

### ISSUE THREAD

**Issue by meilin996** [ChestnutHeng/Wudao-dict#21]
rm掉旧版本，clone新版本安装后不能使用
```
$ wd fuck
Error: Connection out of time
Traceback (most recent call last):
  File "WudaoCommand.py", line 135, in <module>
    main()
  File "WudaoCommand.py", line 131, in main
    app.query()
  File "WudaoCommand.py", line 77, in query
    server_context = self.client.get_word_info(self.word).strip()
  File "/home/linmei/tools/wudao-dict/wudao-dict/src/WudaoClient.py", line 29, in get_word_info
    self.client.sendall(word.encode('utf-8'))
BrokenPipeError: [Errno 32] Broken pipe
```

**Comment by meilin996** [comment]
重启一下好了，应该是端口的问题吧=。=
