### ISSUE TITLE
BrokenPipeError: [Errno 32] Broken pipe

### ISSUE THREAD

**Issue by fenguge** [ChestnutHeng/Wudao-dict#26]
Error: Connection out of time
Traceback (most recent call last):
  File "WudaoCommand.py", line 135, in <module>
    main()
  File "WudaoCommand.py", line 131, in main
    app.query()
  File "WudaoCommand.py", line 77, in query
    server_context = self.client.get_word_info(self.word).strip()
  File "/home/micheallin/Workspace/github/Wudao-dict-master/wudao-dict/src/WudaoClient.py", line 29, in get_word_info
    self.client.sendall(word.encode('utf-8'))
BrokenPipeError: [Errno 32] Broken pipe

**Comment by erickwoc** [comment]
同样的问题
```
[eric@eric-PC wudao-dict]$ wd hello
Error: Connection out of time
Traceback (most recent call last):
  File "WudaoCommand.py", line 135, in <module>
    main()
  File "WudaoCommand.py", line 131, in main
    app.query()
  File "WudaoCommand.py", line 77, in query
    server_context = self.client.get_word_info(self.word).strip()
  File "/home/eric/wudao-dict/wudao-dict/src/WudaoClient.py", line 29, in get_word_info
    self.client.sendall(word.encode('utf-8'))
BrokenPipeError: [Errno 32] Broken pipe
```

**Comment by erickwoc** [comment]
取消了全局代理，然后注销重新登录后恢复正常
