### ISSUE TITLE
在kali下无法使用， 错误信息如下， 请问如何解决?

### ISSUE THREAD

**Issue by JohannesLiu** [ChestnutHeng/Wudao-dict#28]
系统: kali-2018.2
终端: gnome-terminal
指令:
root@kali:~/wudao-dict/wudao-dict# ./setup.sh
Setup Finished! 
use wd [OPTION]... [WORD] to query the word.
自动补全会在下次打开命令行时启用
或者手动运行 source ~/.bashrc
root@kali:~/wudao-dict/wudao-dict# wd hello
Traceback (most recent call last):
  File "WudaoCommand.py", line 10, in <module>
    from src.WudaoClient import WudaoClient
  File "/root/wudao-dict/wudao-dict/src/WudaoClient.py", line 3, in <module>
    import socket
  File "/usr/lib/python3.6/socket.py", line 49, in <module>
    import _socket
ModuleNotFoundError: No module named '_socket'
Python版本:
root@kali:~/wudao-dict/wudao-dict# python3
Python 3.6.4 |Anaconda, Inc.| (default, Jan 16 2018, 18:10:19) 
[GCC 7.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> 
[1]+  Stopped                 python3

**Comment by toddyhan** [comment]
@JohannesLiu 你的socket模块没有安装？

```
toddhan@toddhanPC:~$ python3
Python 3.6.5 (default, Apr  1 2018, 05:46:30) 
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import socket
>>> 

```

**Comment by JohannesLiu** [comment]
好的，感谢！
