### ISSUE TITLE
查询词汇出错，uninstall 后再安装也无法解决问题

### ISSUE THREAD

**Issue by xiankunxu** [ChestnutHeng/Wudao-dict#33]
安装好后，任意查询词汇：
xiankun@xiankun-PC:~/Softwares/Wudao-dict/wudao-dict$ wd university
出现如下错误：
Traceback (most recent call last):
  File "WudaoCommand.py", line 118, in <module>
    main()
  File "WudaoCommand.py", line 114, in main
    app.query()
  File "WudaoCommand.py", line 74, in query
    self.history_manager.add_item(self.word)
  File "/home/xiankun/Softwares/Wudao-dict/wudao-dict/src/UserHistory.py", line 30, in add_item
    self.content = json.load(f)
  File "/usr/lib/python3.4/json/__init__.py", line 268, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/usr/lib/python3.4/json/__init__.py", line 318, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.4/json/decoder.py", line 343, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.4/json/decoder.py", line 361, in raw_decode
    raise ValueError(errmsg("Expecting value", s, err.value)) from None
ValueError: Expecting value: line 1 column 1 (char 0)

运行uninstall.sh后再安装也无法解决问题，是否是我的python版本的问题？

**Comment by dadadaheiguo** [comment]
应该是python版本问题，我换了python版本就好了
