### ISSUE TITLE
经常出现链接超时怎么办，等很久也不出单词翻译结果

### ISSUE THREAD

**Issue by wuqingze** [ChestnutHeng/Wudao-dict#65]
·Traceback (most recent call last):
  File "WudaoCommand.py", line 195, in <module>
    main()
  File "WudaoCommand.py", line 190, in main
    app.param_parse()
  File "WudaoCommand.py", line 69, in param_parse
    self.client.close()
  File "/home/nong/wudao-dict/wudao-dict/src/WudaoClient.py", line 41, in close
    self.connect()
  File "/home/nong/wudao-dict/wudao-dict/src/WudaoClient.py", line 17, in connect
    self.client.connect(("0.0.0.0", 23764))
·

**Comment by ChestnutHeng** [comment]
看一下Wudao-Dict/wudao-dict/usr/server.log 是不是端口被占用了？重试可以解决吗？
