### ISSUE TITLE
Connection out of time

### ISSUE THREAD

**Issue by iammrallblue** [ChestnutHeng/Wudao-dict#66]
Error: Connection out of time
Traceback (most recent call last):
  File "WudaoCommand.py", line 195, in <module>
    main()
  File "WudaoCommand.py", line 191, in main
    app.query(app.word)
  File "WudaoCommand.py", line 103, in query
    server_context = self.client.get_word_info(word).strip()
  File "/home/johs/wudao-dict/wudao-dict/src/WudaoClient.py", line 29, in get_word_info
    self.client.sendall(word.encode('utf-8'))
BrokenPipeError: [Errno 32] Broken pipe

**Comment by ChestnutHeng** [comment]
看一下Wudao-Dict/wudao-dict/usr/server.log 是不是端口被占用了？重试可以解决吗？
