### ISSUE TITLE
Error: Traceback (most recent call last)

### ISSUE THREAD

**Issue by laraws** [ChestnutHeng/Wudao-dict#72]
When I ran the wd command to get English translation  from Chinese input, ther error displayed  below:

```
➜  ~ wd 符号
Traceback (most recent call last):
  File "WudaoCommand.py", line 195, in <module>
    main()
  File "WudaoCommand.py", line 191, in main
    app.query(app.word)
  File "WudaoCommand.py", line 105, in query
    word_info = json.loads(server_context)
  File "/usr/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

```

Why didn't this happen? How to solve it?

**Comment by Syize** [comment]
使用""将汉字括起来

**Comment by laraws** [comment]
> 使用""将汉字括起来

I have tried it and it outputed the same error.
