### ISSUE TITLE
BrokenPipeError: [Errno 32] Broken pipe

### ISSUE THREAD

**Issue by DachunKai** [ChestnutHeng/Wudao-dict#74]
`Error: Connection out of time
Traceback (most recent call last):
  File "WudaoCommand.py", line 195, in <module>
    main()
  File "WudaoCommand.py", line 191, in main
    app.query(app.word)
  File "WudaoCommand.py", line 103, in query
    server_context = self.client.get_word_info(word).strip()
  File "/home/liam/Downloads/wudao-dict/wudao-dict/src/WudaoClient.py", line 29, in get_word_info
    self.client.sendall(word.encode('utf-8'))
`

**Comment by ChestnutHeng** [comment]
请问是哪个词呢
