### ISSUE TITLE
Functioning Abnormally and Canot Be Used Any More

### ISSUE THREAD

**Issue by OutGazing** [ChestnutHeng/Wudao-dict#9]
Here below is the screen output after I "wd ####" a word
------------------------------------
^CTraceback (most recent call last):
  File "WudaoCommand.py", line 118, in <module>
    main()
  File "WudaoCommand.py", line 114, in main
    app.query()
  File "WudaoCommand.py", line 68, in query
    server_context = self.client.get_word_info(self.word).strip()
  File "/home/HOST/wudao-dict/wudao-dict/src/WudaoClient.py", line 27, in get_word_info
    self.connect()
  File "/home/HOST/wudao-dict/wudao-dict/src/WudaoClient.py", line 17, in connect
    self.client.connect(("0.0.0.0", 2376))
KeyboardInterrupt

**Comment by ChestnutHeng** [comment]
What is your Linux distribution?

**Comment by OutGazing** [comment]
My linux is Ubuntu LTS 16.04 - 64bit

**Comment by OutGazing** [comment]
Please advise how can I uninstall it from my Ubuntu 16.04？

**Comment by ChestnutHeng** [comment]
`sudo rm /usr/bin/wd`
and then delete this git repo.
I have no idea about your question
