### ISSUE TITLE
经常会出现connection time out 

### ISSUE THREAD

**Issue by kirkzhangtech** [ChestnutHeng/Wudao-dict#91]
kirk@pro15:~$ wd explicitely
Error: Connection out of time
Traceback (most recent call last):
  File "/home/kirk/github_workspace/wudao-dict/wudao-dict/WudaoCommand.py", line 195, in <module>
    main()
  File "/home/kirk/github_workspace/wudao-dict/wudao-dict/WudaoCommand.py", line 191, in main
    app.query(app.word)
  File "/home/kirk/github_workspace/wudao-dict/wudao-dict/WudaoCommand.py", line 103, in query
    server_context = self.client.get_word_info(word).strip()
  File "/home/kirk/github_workspace/wudao-dict/wudao-dict/src/WudaoClient.py", line 29, in get_word_info
    self.client.sendall(word.encode('utf-8'))
BrokenPipeError: [Errno 32] Broken pipe
kirk@pro15:~$

**Comment by somiceast** [comment]
这是来自QQ邮箱的休眠期自动回复邮件。你好，我最近正在休眠中，无法亲自回复你的邮件。我将在休眠期结束后，尽快给你回复。
